export const selectValue = [
  { name: "Gray", id: "gray" },
  { name: "Gold", id: "gold" },
  { name: "Bronze", id: "bronze" },
  { name: "Brown", id: "brown" },
  { name: "Yellow", id: "yellow" },
  { name: "Amber", id: "amber" },
  { name: "Orange", id: "orange" },
  { name: "Tomato", id: "tomato" },
  { name: "Red", id: "red" },
  { name: "Ruby", id: "ruby" },
  { name: "Crimson", id: "crimson" },
  { name: "Pink", id: "pink" },
  { name: "Plum", id: "plum" },
  { name: "Purple", id: "purple" },
  { name: "Violet", id: "violet" },
  { name: "Iris", id: "iris" },
  { name: "Indigo", id: "indigo" },
  { name: "Blue", id: "blue" },
  { name: "Cyan", id: "cyan" },
  { name: "Teal", id: "teal" },
  { name: "Jade", id: "jade" },
  { name: "Green", id: "green" },
  { name: "Grass", id: "grass" },
  { name: "Lime", id: "lime" },
  { name: "Mint", id: "mint" },
  { name: "Sky", id: "sky" }
]
